apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-a-app1-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://your.git.repo/here.git
    targetRevision: HEAD
    path: apps/team-a/app1/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: team-a-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
